function naca0016pane = importPanelisation(filename, dataLines)
%IMPORTFILE Import data from a text file
%  NACA0016PANE = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  NACA0016PANE = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  naca0016pane = importfile("C:\Users\aless\OneDrive - Politecnico di Milano\PoliMi\MAGISTRALE\1 ANNO\Aerodinamica\Laboratorio_Hess_Smith\naca_0016_pane", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 29-Nov-2022 09:56:11

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["x_pane", "y_pane", "Var3"];
opts.SelectedVariableNames = ["x_pane", "y_pane"];
opts.VariableTypes = ["double", "double", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Specify variable properties
opts = setvaropts(opts, "Var3", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Var3", "EmptyFieldRule", "auto");
opts = setvaropts(opts, "x_pane", "TrimNonNumeric", true);
opts = setvaropts(opts, "x_pane", "ThousandsSeparator", ",");

% Import the data
naca0016pane = readtable(filename, opts);

end